config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :director do
    get 'projects/trash'
    resources :projects

    get 'dashboard' => 'dashboard#index'
    get '/' => 'dashboard#index'
  end

  get 'news/index'
  get 'welcome/about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/trash_bin.rb
module TrashBin
  module ClassMethods
    def trash_bin
      self.where(trash:true)
    end

    def available
      self.where(trash: false)
    end
  end

  def put_to_trash
    unless self.trash
      update(trash:true)
    else
      destroy
    end
  end

  def restore
    update(trash:false)
  end

  def self.included(receiver)
    receiver.extend(ClassMethods)
  end

end

app/models/director_record.rb
class DirectorRecord < ActiveRecord::Base
  include TrashBin
  self.abstract_class = true

  #def name=(val)
  #  write_attribute(:name, val.downcase)
  #end

  class << self
    def to_options
      self.where(trash: false).collect do |item|
        {
            id: item[:id],
            value: item[:name]
        }
      end
    end

    def to_names
      self.available.collect do |item|
        item[:name]
      end
    end
  end
end

app/models/project.rb
class Project < DirectorRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/director/dashboard_controller.rb
class Director::DashboardController < DirectorController
  def index
  end

  def set_title
    @title = "Dashboard"
    @current_menu = "dashboard"
  end
end

app/controllers/director/projects_controller.rb
class Director::ProjectsController < DirectorController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def trash
  end

  def create
  end

  def update
  end

  def destroy
  end

  def set_title
    @title = "Projects"
    @current_menu = "projects"
  end
end

app/controllers/director_controller.rb
class DirectorController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'director'

  # before_action :authenticate_user_from_token!

  before_action :authenticate_user!
  before_action :set_title

  def set_title
    @title = "No Title"
  end

  #def authenticate_user_from_token!
  #  user_token = params[:user_token].presence
  #  user = user_token && User.find_by_authentication_token(user_token.to_s)
  #
  #  if user
  #    # Notice we are passing store false, so the user is not
  #    # actually stored in the session and a token is needed
  #    # for every request. If you want the token to work as a
  #    # sign in token, you can simply remove store: false.
  #    sign_in user, store: false
  #  end
  #end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/director/dashboard_helper.rb
module Director::DashboardHelper
end

app/helpers/director/projects_helper.rb
module Director::ProjectsHelper
end

app/helpers/director_helper.rb
module DirectorHelper
  def side_menu(active)
    menu_items = [
        {
            text: 'dashboard',
            url: director_dashboard_path,
            icon: 'tachometer'
        },
        {
            text: 'projects',
            url: director_projects_path,
            icon: 'building'
        },
        {
            text: '____',
            url: ''
        },
        {
            text: 'settings',
            url: "#",
            icon: 'picture-o'
        },
        {
            text: 'sign out',
            url: "#",
            icon: 'dollar'
        },
        {
            text: 'bugs',
            url: "#",
            icon: 'bug'
        }

    ]
    menu = menu_items.inject('') do |acc, item|
      if item[:text].eql? '____'
        acc + '<div class="separator"></div>'
      else
        acc + "<a href='#{item[:url]}'><div class='menu-item #{active == item[:text] ? 'menu-active' : ''}'><li><div class='icon'>#{icon(item[:icon])}</div><div class='hidden-xs menu-text'>#{sanitize item[:text]}</div></li></div></a>"
      end
    end
    "<ul>#{menu}</ul>".html_safe
  end

  def side_bar(active)
    "<div class='side-bar'><div class='logo'><div class='hidden-sm'>FENNEC</div><div class='visible-sm'>F</div></div>#{side_menu(active)}</div>".html_safe
  end

  def title(text)
    "<div class='page-title'><h1>#{sanitize text}</h1></div>".html_safe
  end

  def section_menu(menu)
    menu = [] unless menu

    html_str = menu.inject('<ul class="section-menu">') do |result, item|
      a_class = 'button-gray'
      a_class = 'button-red' if item[:color].eql? 'danger'
      result + "<li><a class='button #{a_class}' href='#{item[:url]}'>#{icon(item[:icon])} #{sanitize item[:text]}</a></li>"
    end
    html_str += '</ul>'
    html_str.html_safe
  end

  def show_errors(object)
    html_str = ''
    if object.errors.any?
      messages = object.errors.full_messages.inject('') { |res, item |  res + "<li>#{item}</li>"}
      html_str = "<div class='system-message system-error'>
                      <div class='row'>
                        <div class='col-sm-1 error-icon'>#{icon 'exclamation-circle', class: 'fa-2x'}</div>
                        <div class='col-sm-6'>
                          <h4>#{pluralize(object.errors.count, 'Error')}</h4>
                          <p><ul>
                            #{messages}
                          </ul></p>
                        </div>
                      </div>
                    </div>"
    end
    html_str.html_safe
  end

  def show_notice(text)
    html_str = ''
    if text
      html_str = "<div class='system-message system-info'>
                      <div class='row'>
                        <div class='col-sm-1 info-icon'>#{icon 'info-circle', class: 'fa-2x'}</div>
                        <div class='col-sm-6'>
                          <h4>Information</h4>
                          <p>
                            #{sanitize text}
                          </p>
                        </div>
                      </div>
                    </div>"
    end
    html_str.html_safe
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/director/dashboard/index.html.haml
%p Find me in app/views/director/dashboard/index.html.haml

app/views/director/projects/create.html.haml
%h1 Director::Projects#create
%p Find me in app/views/director/projects/create.html.haml

app/views/director/projects/destroy.html.haml
%h1 Director::Projects#destroy
%p Find me in app/views/director/projects/destroy.html.haml

app/views/director/projects/edit.html.haml
%h1 Director::Projects#edit
%p Find me in app/views/director/projects/edit.html.haml

app/views/director/projects/index.html.haml
%p Find me in app/views/director/projects/index.html.haml

app/views/director/projects/new.html.haml
%h1 Director::Projects#new
%p Find me in app/views/director/projects/new.html.haml

app/views/director/projects/show.html.haml
%h1 Director::Projects#show
%p Find me in app/views/director/projects/show.html.haml

app/views/director/projects/trash.html.haml
%h1 Director::Projects#trash
%p Find me in app/views/director/projects/trash.html.haml

app/views/director/projects/update.html.haml
%h1 Director::Projects#update
%p Find me in app/views/director/projects/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FennecCore
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-toggleable-md.navbar-fixed-top.top-bar.navbar-inverse
      %button{class: "navbar-toggler navbar-toggler-right collapsed", type: "button", data: {toggle: "collapse", target: "#fennec-navbar"}, aria: {controls: "fennec-navbar", expanded: "false", label: "Toggle navigation"}}
        %span.navbar-toggler-icon
      = link_to 'fennec', root_path, class: "navbar-brand top-bar-logo"
      #fennec-navbar.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            = link_to 'News', news_index_path, class: "nav-link"
          %li.nav-item
            = link_to 'About', welcome_about_path, class: "nav-link"
        %ul.navbar-nav.navbar-right
          %li
            %a{href: '#'}
              %i.fa.fa-question-circle
              .visible-xs-inline
                Help
          %li
            %a{href: '#'}
              %i.fa.fa-cog
              .visible-xs-inline
                Setup
          %li
            = link_to 'Sign-in', "#"
    .container
      = yield

app/views/layouts/director.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Fennec-Core/Director
    = csrf_meta_tags
    = stylesheet_link_tag    'director', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'director', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      .row
        = side_bar(@current_menu)
        .container-fluid.side-bar-offset
          = title(@title)
          = yield

app/views/news/index.html.haml
%h1 News#index
%p Find me in app/views/news/index.html.haml

app/views/welcome/about.html.haml
%h1 Welcome#About
%p Find me in app/views/welcome/about.html.haml

app/views/welcome/index.html.haml
.description
  .jumbotron.page-jumbotron
    %h1 Fennec Open IoT platform
  .row
    .col-sm-12
      .h3
        Simple and fast platform to use as a core for your IoT solution
  .row
    .col-md-3
      .header
        %h2
          Connect
      .text
        %p
          Just connect devices to the application and start getting data
    .col-md-3
      .header
        %h2
          Collect
      .text
        %p
          All data from devices will be stored in database
    .col-md-3
      .header
        %h2
          Manage
      .text
        %p
          Device can be managed with security over Internet
    .col-md-3
      .header
        %h2
          Analyze
      .text
        %p
          As soon as all data stored in a database, the information can be used for tracking and controlling other devices